name: Pull upstream changes

on:
  schedule:
    - cron: '32 * * * *'

jobs:
  update-snapshot:
    name: Update snapshots
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: Synchronize
        run: |
          ./sync.sh

      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.SG_REPO_GH_APP_ID }}
          private_key: ${{ secrets.SG_REPO_GH_APP_PRIV_KEY }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}
          branch: automated/catch-up
          labels: "automated pr"
          commit-message: Catch up with Satyrographos Repo
          title: '[Automated] Catch up with Satyrographos Repo'
          body: |
            Catch up with Satyrographos Repo
