name: Pull upstream changes

on:
  schedule:
    - cron: '32 * * * *'

jobs:
  update-snapshot:
    name: Update snapshots
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Update submodules
        run: |
          cd satyrographos-repo
          git pull

      - name: Copy workflows
        run: |
          cp satyrographos-repo/.github/workflows/{ci-comment,pr-followup,pr,snapshot}.yaml .github/workflows

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Pull upstream changes
